component: scf
name: vercel-proxy-app

inputs:
  name: vercel-proxy
  src: ./
  handler: index.main_handler
  runtime: Nodejs12.16
  region: ap-guangzhou
  description: Vercel API Proxy
  memorySize: 64
  timeout: 10
  excludes:
    - node_modules/**
    - .git/**
    - .env
    - .env.example
    - README.md
  environment:
    variables:
      TARGET_HOST: ${env:TARGET_HOST}
  events:
    - functionUrl:
        parameters:
          authType: NONE
